# Generated by Django 2.2.2 on 2019-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_1', models.CharField(max_length=100)),
                ('subcategory_1', models.CharField(max_length=100)),
                ('category_2', models.CharField(max_length=100)),
                ('subcategory_2', models.CharField(max_length=100)),
                ('pub_date_1', models.DateField()),
                ('pub_date_2', models.DateField()),
                ('image_1', models.ImageField(default='', upload_to='shop/images')),
                ('image_2', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
