# Generated by Django 2.2.2 on 2019-07-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productheader',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
