# Generated by Django 2.2.2 on 2019-07-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='productheader',
            name='rating',
            field=models.FloatField(default=3.0),
        ),
    ]
