# Generated by Django 2.2.2 on 2019-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
